#!/bin/sh

APP=/var/lib/tomcat6/webapps/ROOT
INCOMING=~/apps/incoming/

cd $INCOMING

files=`ls | sort`

for f in $files
do
  echo "Installing WAR from: $f"
  sudo unzip -oq $f -d $APP
  mv $f ~/apps/complete/$f
done
